version: '3.8'

services:
  web:
    build: .
    container_name: nginx-php
    ports:
      - "5000:5000"
    volumes:
      - ./app:/var/www/html
      # linux
      - ~/workspace/designintoto/git/Framework/DDMB-Framework/P4 Dev/assets/library FLG25:/var/www/html/content
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  php:
    image: php:8.2-fpm
    container_name: php-fpm
    volumes:
      - ./app:/var/www/html
      # so php can read and write into that volume
      - /home/hugo/workspace/designintoto/git/Framework/DDMB-Framework:/var/www/html/content
    networks:
      - app-network
networks:
  app-network:
    driver: bridge